INSERT INTO ITEM VALUES (1, 'Mayonesa', 'SALSAS', false, 'CREATED', 'jcrespo', CURRENT_TIMESTAMP);
INSERT INTO ITEM VALUES (2, 'Manzana', 'COMIDA', true, 'CREATED', 'jcrespo', CURRENT_TIMESTAMP);
INSERT INTO ITEM VALUES (3, 'Platanos', 'COMIDA', false, 'CREATED', 'jcrespo', CURRENT_TIMESTAMP);
INSERT INTO ITEM VALUES (4, 'Arroz', 'COMIDA', false, 'CREATED', 'jcrespo', CURRENT_TIMESTAMP);
INSERT INTO ITEM VALUES (5, 'Salsa de Tomate', 'SALSAS', false, 'CREATED', 'jcrespo', CURRENT_TIMESTAMP);
INSERT INTO ITEM VALUES (6, 'Enlatados', 'COMIDA', false, 'CREATED', 'jcrespo', CURRENT_TIMESTAMP);


INSERT INTO CAPACIDAD VALUES (1, 1, 100);
INSERT INTO CAPACIDAD VALUES (2, 1, 1000);
INSERT INTO CAPACIDAD VALUES (3, 2, 1000);
INSERT INTO CAPACIDAD VALUES (4, 3, 1000);
INSERT INTO CAPACIDAD VALUES (5, 4, 1000);
INSERT INTO CAPACIDAD VALUES (6, 5, 100);
INSERT INTO CAPACIDAD VALUES (7, 5, 1000);
INSERT INTO CAPACIDAD VALUES (8, 6, 100);
INSERT INTO CAPACIDAD VALUES (9, 6, 1000);


INSERT INTO ENVASE VALUES (1, 1, 'BOTELLA');
INSERT INTO ENVASE VALUES (2, 1, 'CAJA');
INSERT INTO ENVASE VALUES (3, 2, 'CAJA');
INSERT INTO ENVASE VALUES (4, 3, 'CAJA');
INSERT INTO ENVASE VALUES (5, 4, 'CAJA');
INSERT INTO ENVASE VALUES (6, 5, 'BOTELLA');
INSERT INTO ENVASE VALUES (7, 5, 'CAJA');
INSERT INTO ENVASE VALUES (8, 6, 'CAJA');